# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setTabletTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.showvirusbutton = QtWidgets.QPushButton(self.centralwidget)
        self.showvirusbutton.setGeometry(QtCore.QRect(1382, 150, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showvirusbutton.setFont(font)
        self.showvirusbutton.setText("")
        self.showvirusbutton.setObjectName("showvirusbutton")
        self.showchartbutton = QtWidgets.QPushButton(self.centralwidget)
        self.showchartbutton.setGeometry(QtCore.QRect(102, 150, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showchartbutton.setFont(font)
        self.showchartbutton.setText("")
        self.showchartbutton.setObjectName("showchartbutton")
        self.showlocationbutton = QtWidgets.QPushButton(self.centralwidget)
        self.showlocationbutton.setGeometry(QtCore.QRect(742, 150, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showlocationbutton.setFont(font)
        self.showlocationbutton.setText("")
        self.showlocationbutton.setObjectName("showlocationbutton")
        self.exitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.exitbutton.setGeometry(QtCore.QRect(1382, 650, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.exitbutton.setFont(font)
        self.exitbutton.setText("")
        self.exitbutton.setObjectName("exitbutton")
        self.showperiodbutton = QtWidgets.QPushButton(self.centralwidget)
        self.showperiodbutton.setGeometry(QtCore.QRect(102, 650, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showperiodbutton.setFont(font)
        self.showperiodbutton.setText("")
        self.showperiodbutton.setObjectName("showperiodbutton")
        self.showpestsbutton = QtWidgets.QPushButton(self.centralwidget)
        self.showpestsbutton.setGeometry(QtCore.QRect(742, 650, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showpestsbutton.setFont(font)
        self.showpestsbutton.setText("")
        self.showpestsbutton.setObjectName("showpestsbutton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 580, 1920, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dateLable = QtWidgets.QLabel(self.centralwidget)
        self.dateLable.setGeometry(QtCore.QRect(0, 0, 1920, 80))
        self.dateLable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateLable.setText("")
        self.dateLable.setTextFormat(QtCore.Qt.RichText)
        self.dateLable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateLable.setObjectName("dateLable")
        self.backgroundlable = QtWidgets.QLabel(self.centralwidget)
        self.backgroundlable.setGeometry(QtCore.QRect(0, 0, 1923, 1083))
        self.backgroundlable.setAutoFillBackground(True)
        self.backgroundlable.setText("")
        self.backgroundlable.setObjectName("backgroundlable")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(640, 85, 3, 1080))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(1280, 85, 3, 1080))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 80, 1920, 10))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 0, 1920, 10))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 1080, 1920, 10))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 0, 3, 1040))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.School = QtWidgets.QLabel(self.centralwidget)
        self.School.setGeometry(QtCore.QRect(0, 0, 160, 80))
        self.School.setText("")
        self.School.setObjectName("School")
        self.ShowIPLabel = QtWidgets.QLabel(self.centralwidget)
        self.ShowIPLabel.setGeometry(QtCore.QRect(1720, 1020, 200, 60))
        self.ShowIPLabel.setText("")
        self.ShowIPLabel.setObjectName("ShowIPLabel")
        self.backgroundlable.raise_()
        self.label.raise_()
        self.showchartbutton.raise_()
        self.showlocationbutton.raise_()
        self.showperiodbutton.raise_()
        self.showpestsbutton.raise_()
        self.showvirusbutton.raise_()
        self.exitbutton.raise_()
        self.dateLable.raise_()
        self.line.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_3.raise_()
        self.line_2.raise_()
        self.School.raise_()
        self.ShowIPLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
